language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
solution: RestWithASPNETUdemy.sln
before_install:
  - sudo apt-get update
script:
  - cd RestWithASPNETUdemy\ 01\ -\ Calculator/
  - echo "Entered /RestWithASPNETUdemy 01 - Calculator/."
  - dotnet restore
  - dotnet build
