sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 2.0.0
python:
  - "3.6"
services: docker
before_install:
  - cd RestWithASPNETUdemy\ 20\ -\ Final\ Release/
  - echo "RestWithASPNETUdemy\ 20\ -\ Final\ Release/."
script:
  - docker-compose build 
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin  
deploy:
  provider: script
  script:
    docker push leandrocgsi/restwithaspnetudemy-api;
  on:
    branch: master
notifications:
  email: false 
